In [1]:
import numpy as np

In [2]:
x=np.array((2,3,4,5,6),dtype="float")

In [11]:
x=np.zeros((3,4))

In [12]:
print("Type of array:",type(x))

Type of array: <class 'numpy.ndarray'>


In [13]:
print("All zeros in 3,4 array",x)

All zeros in 3,4 array [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
x=np.ones((4,4))

In [15]:
print("All ones in 4,4 array:",x)

All ones in 4,4 array: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:
x=np.full((2,3),7)

In [26]:
print("All 7 in 2,3 array:",x)

All 7 in 2,3 array: [[7 7 7]
 [7 7 7]]


In [30]:
x=np.eye(3,3)

In [31]:
print("Diagonal as 1 other as 0",x)

Diagonal as 1 other as 0 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
x=np.arange(2,10,3)

In [35]:
print("Increment by 3 from 2 until end 3 reach",x)

Increment by 3 from 2 until end 3 reach [2 5 8]


In [36]:
x=np.linspace(7,10,10)

In [ ]:
print()