In [1]:
import numpy as np

In [4]:
x=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])

In [5]:
print("Printing array x:",x)

Printing array x: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
print("Printing the value of [0][0] and [1][1]",x[0][0],x[1][1])

Printing the value of [0][0] and [1][1] 0 5


In [7]:
print("Q.1 Display value 0,1",x[0:1,0:2])

Display value 0,1 [[0 1]]


In [10]:
print("Q.2 Display value 1,2,3",x[0:1,1:4])

Display value 1,2,3 [[1 2 3]]


In [21]:
print("Q.3 Display value 4:",x[1:2,0:1])

Q.3 Display value 4: [[4]]


In [23]:
print("Display value [[5,6,7][9,10,11]]:",x[1:3,1:4])

Display value [[5,6,7][9,10,11]]: [[ 5  6  7]
 [ 9 10 11]]


In [24]:
a=np.array([[8,20,24,25],[30,35,36,40],[42,43,47,50],[49,51,52,53]])

In [25]:
print("Arrray a:",a)

Arrray a: [[ 8 20 24 25]
 [30 35 36 40]
 [42 43 47 50]
 [49 51 52 53]]


In [26]:
print("Display value [[35,36][43,47]]:",a[1:3,1:3])

Display value [[35,36][43,47]]: [[35 36]
 [43 47]]


In [29]:
print("Display value[[43,47,50][51,52,53]]:",a[2:4,1:4])

Display value[[43,47,50][51,52,53]]: [[43 47 50]
 [51 52 53]]


In [40]:
print("Display value [[24,25][36,40]]:",a[0:2,2:4])

Display value [[24,25][36,40]]: [[24 25]
 [36 40]]
